services:
  mariadb:
    image: mariadb:12
    container_name: quarkus-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: userdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: quarkus-native-users
    container_name: quarkus-app
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mariadb://mariadb:3306/userdb
      QUARKUS_DATASOURCE_USERNAME: appuser
      QUARKUS_DATASOURCE_PASSWORD: apppassword
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          memory: 64m

  frontend:
    build:
      context: ../front
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - app
    environment:
      - API_URL=http://quarkus:8081        
